name: build-image
on:
  push:
    branches: ['v2']
    paths:
      - "build.trigger"

#  schedule:
#    - # 国际时间 19:17 执行，北京时间3:17  ↙↙↙ 改成你想要每天自动执行的时间
#    - cron: '17 19 * * *'
permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: get_certd_version
        id: get_certd_version
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const pnpmWorkspace = "./pnpm-workspace.yaml";
            fs.removeSync(jsonFilePath)
            
            const jsonFilePath = "./packages/ui/certd-server/package.json";
            const jsonContent = fs.readFileSync(jsonFilePath, 'utf-8');
            console.log(jsonContent)
            const pkg = JSON.parse(jsonContent)
            // 打印 JSON 文件内容
            console.log("certd_version:",pkg.version);
            // 输出 JSON 对象，可以在后续步骤中使用
            return {"version":"0.0.5"};

      - name: Set up the working directory
        run: |
          mkdir -p ./packages/ui/
        working-directory: ./packages/ui/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.aliyun_cs_username }}
          password: ${{ secrets.aliyun_cs_password }}

      - name: Build and push
        uses: docker/build-push-action@v6.5.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-shenzhen.aliyuncs.com/handsfree/certd:${{steps.get_certd_version.outputs.version}}
